build-frontend-code-job:
  stage: build
  only:
    changes:
    - frontend/*
  script:        
    - cd frontend
    - npm install  #-D sonarqube-scanner
    - npm run build
    - echo "FRONTEND_BUILD_ARTEFACT_URL=$CI_JOB_URL/artifacts/download?file_type=archive" >> build.env
    - echo "${CI_JOB_URL}"
  artifacts:
    paths:
      - frontend/dist/frontend 

slack-notification-frontend:
  needs:
    - build-frontend-code-job
  variables:
    DATA: '{"text":"2.2 Собран Frontend приложения. Ссылка на артефакт: $CI_JOB_URL/artifacts/download?file_type=archive"}'
    CONTENT_TYPE: 'Content-type: application/json'
    SLACK_WEBHOOK: 'https://hooks.slack.com/services/...'
  stage: notify
  only:
    changes:
    - frontend/*
  script:
    'curl -X POST -H "$CONTENT_TYPE" --data "$DATA" "$SLACK_WEBHOOK"'
